harnessApiVersion: '1.0'
type: PIPELINE
description: 4 Services in Order
pipelineStages:
- type: ENV_STATE
  name: Deploy Service A
  parallel: false
  skipCondition:
    type: DO_NOT_SKIP
  stageName: STAGE 1
  workflowName: Deploy Service A
  workflowVariables:
  - entityType: ENVIRONMENT
    name: Environment
    value: Staging
  - entityType: INFRASTRUCTURE_DEFINITION
    name: InfraDefinition_KUBERNETES
    value: az-staging
- type: ENV_STATE
  name: Deploy Service B
  parallel: true
  skipCondition:
    type: DO_NOT_SKIP
  stageName: STAGE 1
  workflowName: Deploy Service B
  workflowVariables:
  - entityType: ENVIRONMENT
    name: Environment
    value: Staging
  - entityType: INFRASTRUCTURE_DEFINITION
    name: InfraDefinition_KUBERNETES
    value: az-staging
- type: ENV_STATE
  name: Deploy Service C
  parallel: false
  skipCondition:
    type: DO_NOT_SKIP
  stageName: STAGE 2
  workflowName: Deploy Service C
  workflowVariables:
  - entityType: ENVIRONMENT
    name: Environment
    value: Staging
  - entityType: INFRASTRUCTURE_DEFINITION
    name: InfraDefinition_KUBERNETES
    value: az-staging
- type: ENV_STATE
  name: Deploy Service D
  parallel: true
  skipCondition:
    type: DO_NOT_SKIP
  stageName: STAGE 2
  workflowName: Deploy Service D
  workflowVariables:
  - entityType: ENVIRONMENT
    name: Environment
    value: Staging
  - entityType: INFRASTRUCTURE_DEFINITION
    name: InfraDefinition_KUBERNETES
    value: az-staging
tags:
  Pipeline: ${workflow.pipelineDeploymentUuid}
